version: 2
project_name: ghpm

builds:
  - id: ghpm
    main: .
    binary: ghpm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm

archives:
  - id: ghpm
    ids:
      - ghpm
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - doc/manifest-reference.md
      - examples/**/*
  - id: ghpm-binary
    ids:
      - ghpm
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}_bin"

checksum:
  name_template: "checksums.txt"
